### ISSUE TITLE
به به کیف نمودیم

### ISSUE THREAD

**Issue by Masihgh** [RealMrHex/hex-kit#1]
این یک مشکل نیست به فهموم تمجید و ستایش همچین چیز خوبیه 
کیف کردم میخوای یسری مطلب توی سایتا  بزار انگلیسی ملت دانلود میکنن کیف میکنن
خواستی میتونم با پایتون برات توسعه بدم کراس پلتفورم همینو :)

**Comment by RealMrHex** [comment]
Hello
Thank you very much for your constructive feedback!
Mac and Linux versions will be available soon and then I will publish the articles publicly!
I'm glad you took the time to review this tool!
I wish you luck
